
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
remote:
  - platform: xiaomi_miio
    host: 192.168.0.145
    token: c2abc0497fb4ebdd04b163c266ec5912
    slot: 1
    timeout: 30
    hidden: false
